$font = JetBrains Mono Nerd Font

general {
    hide_cursor = true
    ignore_empty_input = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/lockscreen.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    inner_color = rgb(24283b)
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgb(7aa2f7)
    check_color = rgb(9ece6a)
    fail_color = rgb(f7768e)

    font_color = rgb(c0caf5)
    fade_on_empty = false

    font_family = $font
    placeholder_text = <i>Enter Password...</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    position = 0, -80
    halign = center
    valign = center
}

# Clock
label {
    monitor =
    text = $TIME
    color = rgb(bb9af7)
    font_size = 60
    font_family = $font
    position = 0, 100
    halign = center
    valign = center
}

# Greeting
label {
    monitor =
    text = Welcome back, Kishore
    color = rgb(c0caf5)
    font_size = 25
    font_family = $font
    position = 0, 10
    halign = center
    valign = center
}
